"""add learning priorities

Revision ID: 0f291e0b913f
Revises: 80609d020d8d
Create Date: 2026-08-01 04:25:19.140777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f291e0b913f'
down_revision: Union[str, Sequence[str], None] = '80609d020d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_gap', sa.Column('learning_priorities', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json"),))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_gap', 'learning_priorities', server_default=None,)
    # ### end Alembic commands ###
