"""add semantic matches

Revision ID: 213218ae0190
Revises: 3687f21a49b9
Create Date: 2026-08-01 01:40:33.044050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '213218ae0190'
down_revision: Union[str, Sequence[str], None] = '3687f21a49b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_gap', sa.Column('semantic_matches', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json"),))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_gap', 'semantic_matches', server_default=None,)
    # ### end Alembic commands ###
