"""add weighted scoring

Revision ID: 61bbdd872fe5
Revises: 213218ae0190
Create Date: 2026-08-01 03:41:47.265508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61bbdd872fe5'
down_revision: Union[str, Sequence[str], None] = '213218ae0190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_gap', sa.Column('matched_weight', sa.Integer(), nullable=False, server_default="0",))
    op.add_column('skill_gap', sa.Column('total_weight', sa.Integer(), nullable=False, server_default="0",))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_gap', 'total_weight')
    op.drop_column('skill_gap', 'matched_weight')
    # ### end Alembic commands ###
