"""add learning roadmap

Revision ID: 6e8aadc9f990
Revises: ceb666e916a6
Create Date: 2026-08-01 23:35:08.041129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8aadc9f990'
down_revision: Union[str, Sequence[str], None] = 'ceb666e916a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_gap', sa.Column('learning_roadmap', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_gap', 'learning_roadmap')
    # ### end Alembic commands ###
