"""add ai feedback

Revision ID: 80609d020d8d
Revises: 61bbdd872fe5
Create Date: 2026-08-01 04:05:45.615908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80609d020d8d'
down_revision: Union[str, Sequence[str], None] = '61bbdd872fe5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_gap', sa.Column('ai_feedback', sa.Text(), nullable=False, server_default="",))
    op.alter_column("skill_gap", "ai_feedback", server_default=None,)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_gap', 'ai_feedback')
    # ### end Alembic commands ###
