"""create resume analysis table

Revision ID: 8ec8c827f095
Revises: e118c1a5a457
Create Date: 2026-07-30 14:46:21.297850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ec8c827f095'
down_revision: Union[str, Sequence[str], None] = 'e118c1a5a457'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_analysis',
    sa.Column("id",sa.String(length=36),nullable=False),
    sa.Column("resume_id", sa.String(length=36), nullable=False),
    sa.Column('extracted_skills', sa.JSON(), nullable=False),
    sa.Column('extracted_projects', sa.JSON(), nullable=False),
    sa.Column('extracted_experience', sa.JSON(), nullable=False),
    sa.Column('extracted_education', sa.JSON(), nullable=False),
    sa.Column('resume_score', sa.Integer(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('suggestions', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_analysis')
    # ### end Alembic commands ###
    
    