"""add is_latest to resumes

Revision ID: 924efe576147
Revises: 7c0347e206b4
Create Date: 2026-07-31 02:09:52.005674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '924efe576147'
down_revision: Union[str, Sequence[str], None] = '7c0347e206b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("resumes", sa.Column("is_latest",sa.Boolean(),nullable=False,server_default=sa.true(),),)

    op.alter_column("resumes", "is_latest", server_default=None,)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'is_latest')
    # ### end Alembic commands ###
