"""add interview preparation

Revision ID: 9f83d822b0fe
Revises: 6e8aadc9f990
Create Date: 2026-08-02 00:43:27.739946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f83d822b0fe'
down_revision: Union[str, Sequence[str], None] = '6e8aadc9f990'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_gap', sa.Column('interview_preparation', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_gap', 'interview_preparation')
    # ### end Alembic commands ###
