"""add skill explanations

Revision ID: a3c6bd7a35ac
Revises: 0f291e0b913f
Create Date: 2026-08-01 04:58:09.185976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c6bd7a35ac'
down_revision: Union[str, Sequence[str], None] = '0f291e0b913f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_gap', sa.Column('skill_explanations', sa.JSON(), nullable=False, server_default=sa.text("'[]'::json"),))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_gap', 'skill_explanations')
    # ### end Alembic commands ###
