"""add career report

Revision ID: b3b0b9a8f057
Revises: 9f83d822b0fe
Create Date: 2026-08-02 01:26:07.740469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3b0b9a8f057'
down_revision: Union[str, Sequence[str], None] = '9f83d822b0fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill_gap', sa.Column('career_report', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill_gap', 'career_report')
    # ### end Alembic commands ###
