"""add score breakdown

Revision ID: b677d38ac72a
Revises: 924efe576147
Create Date: 2026-07-31 03:31:09.834548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b677d38ac72a'
down_revision: Union[str, Sequence[str], None] = '924efe576147'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_analysis', sa.Column('score_breakdown', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_analysis', 'score_breakdown')
    # ### end Alembic commands ###
