"""create learning roadmap table

Revision ID: ceb666e916a6
Revises: a3c6bd7a35ac
Create Date: 2026-08-01 21:29:46.709766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb666e916a6'
down_revision: Union[str, Sequence[str], None] = 'a3c6bd7a35ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_roadmap',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('resume_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('roadmap', sa.JSON(), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('learning_roadmap')
    # ### end Alembic commands ###
